name: CI (Windows)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-lint-windows:
    name: Test, Lint & Coverage (Windows)
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path -Path "requirements.txt") {
            pip install -r requirements.txt
          } else {
            Write-Host "No requirements.txt found"
          }

      - name: Lint (flake8)
        shell: pwsh
        run: |
          if (Get-Command flake8 -ErrorAction SilentlyContinue) {
            Write-Host "Running flake8..."
            flake8
          } else {
            Write-Host "flake8 not installed; installing..."
            pip install flake8
            flake8
          }

      - name: Security scan (bandit)
        shell: pwsh
        run: |
          if (Get-Command bandit -ErrorAction SilentlyContinue) {
            Write-Host "Running bandit..."
          } else {
            Write-Host "bandit not found; installing..."
            pip install bandit
          }
          New-Item -ItemType Directory -Path reports -Force | Out-Null
          bandit -r . -f json -o reports\bandit.json || Write-Host "Bandit completed with exit code $LASTEXITCODE"

      - name: Run tests (pytest) and collect coverage
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path reports -Force | Out-Null
          if (Get-Command pytest -ErrorAction SilentlyContinue) {
            pytest --junitxml=reports\junit.xml --cov=./ --cov-report=xml:reports\coverage.xml
          } else {
            Write-Host "pytest not found; installing..."
            pip install pytest pytest-cov
            pytest --junitxml=reports\junit.xml --cov=./ --cov-report=xml:reports\coverage.xml
          }

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: ci-reports-windows
          path: reports/
