name: Build-Test-Deploy to Vercel (Windows)

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        shell: powershell

      - name: Run tests
        run: npm test
        shell: powershell

      - name: Build project
        run: npm run build
        shell: powershell

      # Debug secrets using PowerShell (Windows-safe)
      - name: Debug Vercel secrets
        shell: powershell
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          Write-Host "Checking secrets..."
          if (-not $env:VERCEL_TOKEN) {
            Write-Host "VERCEL_TOKEN is not set!"
            exit 1
          }
          Write-Host ("VERCEL_TOKEN length: {0}" -f $env:VERCEL_TOKEN.Length)
          Write-Host ("VERCEL_PROJECT_ID: {0}" -f $env:VERCEL_PROJECT_ID)
          Write-Host ("VERCEL_ORG_ID: {0}" -f $env:VERCEL_ORG_ID)

      - name: Deploy to Vercel (action)
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
