name: Scheduled Maintenance

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2 AM UTC
  workflow_dispatch:

jobs:
  daily-tasks:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          if (Test-Path "package-lock.json") {
            npm ci
          } else {
            npm install
          }

      - name: Run maintenance script
        run: |
          if (Test-Path "scripts/scheduled-tasks.js") {
            node scripts/scheduled-tasks.js | Out-File -FilePath backup-log.txt -Encoding utf8
          } else {
            "No scheduled-tasks script found. Create scripts/scheduled-tasks.js to perform tasks." | Out-File -FilePath backup-log.txt -Encoding utf8
          }

      - name: Upload backup log
        uses: actions/upload-artifact@v4
        with:
          name: daily-maintenance-log
          path: backups/**
